apiVersion: v1
kind: ConfigMap
metadata:
  name: contract-manager-config
  namespace: contract-manager
data:
  DJANGO_SETTINGS_MODULE: config.settings.production
  DJANGO_DEBUG: "false"
  DJANGO_ALLOWED_HOSTS: "YOUR_DOMAIN"
  DJANGO_CSRF_TRUSTED_ORIGINS: "https://YOUR_DOMAIN"
  REDIS_URL: redis://redis:6379/0
