apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contract-manager

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - media-pvc.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - migration-job.yaml
